### ISSUE TITLE
Security Lab

### ISSUE THREAD

**Issue by skalolazka** [skalolazka/SEBC#6]
TLS didn't work even though I went through all the steps in https://www.cloudera.com/documentation/enterprise/5-9-x/topics/cm_sg_tls_browser.html , swapping step 1 with https://www.cloudera.com/documentation/enterprise/5-9-x/topics/sg_self_signed_tls.html , did it many times very thoroughly, could definitely read with keytool all certificates, all were distributed on all servers. Including screenshot of logs here. In my set-up cloudera-scm-server is running not on the same machine as the Cloudera Management services, so that might have something to do with it, although I doubt it.

**Comment by skalolazka** [comment]
Can't see how to post pictures here, so not a screenshot, but just text part from role log (no other logs have any indicators of the problem):
`

Oct 17, 2:02:51.698 PM | WARN | com.cloudera.cmon.firehose.Main | No descriptor fetched from https://ip-172-31-35-4.eu-central-1.compute.internal:7183 on after 1 tries, sleeping...
-- | -- | -- | --
Oct 17, 2:02:51.817 PM | WARN | com.cloudera.cmf.event.publish.EventStorePublisherWithRetry | Failed to publish event: SimpleEvent{attributes={STACKTRACE=[javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: No trusted certificate found 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884) 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276) 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270) 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341) 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153) 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868) 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:804) 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016) 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312) 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339) 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323) 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563) 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1091) 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) 	at com.cloudera.cmf.BasicScmProxy.authenticate(BasicScmProxy.java:265) 	at com.cloudera.cmf.BasicScmProxy.fetch(BasicScmProxy.java:561) 	at com.cloudera.cmf.BasicScmProxy.getFragmentAndHash(BasicScmProxy.java:651) 	at com.cloudera.cmf.DescriptorAndFragments.newDescriptorAndFragments(DescriptorAndFragments.java:64) 	at com.cloudera.cmon.firehose.Main.main(Main.java:376) Caused by: sun.security.validator.ValidatorException: No trusted certificate found 	at sun.security.validator.SimpleValidator.buildTrustedChain(SimpleValidator.java:384) 	at sun.security.validator.SimpleValidator.engineValidate(SimpleValidator.java:134) 	at sun.security.validator.Validator.validate(Validator.java:260) 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326) 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:107) 	at com.cloudera.enterprise.ssl.ReloadingX509TrustManager.checkServerTrusted(ReloadingX509TrustManager.java:131) 	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:813) 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1323) 	... 16 more ], EXCEPTION_TYPES=[javax.net.ssl.SSLHandshakeException, sun.security.validator.ValidatorException], ROLE=[mgmt-HOSTMONITOR-8a224d1f38c8a0742eba2d38ac9ddbcb], SEVERITY=[IMPORTANT], SERVICE=[mgmt], HOST_IDS=[i-0ec03f8f0422c55ee], LOG_LEVEL=[WARN], ROLE_TYPE=[HOSTMONITOR], CATEGORY=[LOG_MESSAGE], SERVICE_TYPE=[MGMT], HOSTS=[ip-172-31-32-101.eu-central-1.compute.internal], EVENTCODE=[EV_LOG_EVENT]}, content=Exception while getting fetch configDefaults hash: none, timestamp=1539784971679}

`

**Comment by skalolazka** [comment]
I'm sorry, I totally forgot to screenshot the TLS into security/labs/tls-level-one.png - it actually got to the stage of the address being https and the port being 7183, but the Cloudera Management Service was not restarting (see above), so the cluster was not functioning. I am unsure I will have time to turn it up again just for screenshotting, but I showed that it worked to @rsiwicki .

**Comment by skalolazka** [comment]
I will not put "submitted" here yet since the TLS did not work yesterday. I am unsure I will find time to do it today and if it makes sense at all because I felt like I was doing everything right, and the only way left to fix it is to start from scratch, but then again I have done exactly that multiple times already. If I do find the time today, I will try again, otherwise I will mark this as "submitted" today later in the day.

**Comment by skalolazka** [comment]
@cfusi karma helped!!! TLS working

**Comment by cfusi** [comment]
Good lab!
